#!/bin/bash
if [ $(id -u) != 0 ]; then
  echo "please run as root."; exit
fi

read -p "sync? [Y/n]: " SYNC
while true; do
  case $SYNC in
    [yY][eE][sS])
      emerge --sync; break;;
    [nN][oO])
      break;;
    *)
      exit;;
  esac
done

UPDPORTAGE="$(emerge -pv sys-apps/portage | grep -w -c "U")"
if [ $UPDPORTAGE -eq 1 ]; then
  emerge -1v sys-apps/portage
fi

if [ $1 == "-n" ]; then
  emerge -puvDN --quiet-build @world
fi

read -p "extra options? [*/n]: " EXTRA
while true; do
  case $EXTRA in
    [nN][oO])
      emerge -uvDN --quiet-build @world; break;;
    *)
      emerge -uvDN --quiet-build $EXTRA @world; break;;
  esac
done
emerge --depclean
