#!/bin/bash
if [ $(id -u) != 0 ]; then
    echo "please run as root."; exit
fi

read -p "partition? " PARTITION
mount /dev/$PARTITION /boot

read -p "sync? [Y/n]: " SYNC
while true; do
    case $SYNC in
	'Y' | 'y')
	    emerge --sync; break;;
	'N' | 'n')
	    break;;
	*)
	    echo "not understood."; break;;
    esac
done

emerge -puvDN --quiet-build @world
read -p "extra options? [*/n]: " EXTRA
while true; do
    case $EXTRA in
	'N' | 'n')
	    emerge -uvDN --quiet-build @world; break;;
	*)
	    emerge -uvDN --quiet-build $EXTRA @world; break;;
    esac
done
emerge --depclean

read -p "upgrade kernel? [y/N]: " KERN
read -p "jobs? " JOBS
while true; do
    case $KERN in
	Yy)
	    cd /usr/src/linux; cp ../linux-$(uname -r)/.config .;
	    make menuconfig; make -j$JOBS; make modules_install; make install;
	    grub-mkconfig -o /boot/grub/grub.cfg; break;;
	Nn)
	    break;;
	*)
	    echo "not understood."; break;;
    esac
done

emerge --quiet-build @module-rebuild
read -p "reboot? " REBOOT
if [ $REBOOT == Yy ]; then
    reboot;
else
    exit;
fi
